Get asset data
equinor/data-marketplace pull request #37
Opened 2022-06-02 14:02 UTC by aronhoyer

Adds backend support for getting asset data

2022-06-08 06:51 UTC, ovineq requested changes
I think it's time to define types for the returned objects from these API calls. The `any` type isn't very helpful, as it bypasses the typescript compiler. 
Having defined types will help newcomers explore the available data, and should also help in reviewing PRs. 😄

2022-06-08 12:23 UTC, aronhoyer commented on pages/api/assets/[id]/overview.ts
> +        type: attr.type.name.toUpperCase().split(" ").join("_"),
it absolutely would 🥲

2022-06-08 12:24 UTC, aronhoyer commented
> I think it's time to define types for the returned objects from these API calls

@ovineq agree! should types be global or do we want to manually import them for each use?

2022-06-08 14:23 UTC, ovineq commented
> > I think it's time to define types for the returned objects from these API calls
> 
> @ovineq agree! should types be global or do we want to manually import them for each use?

I'm most familiar with them being local and imported. I also have a preference for namespaces for external type definitions. E.g. if I see a type `Collibra.Asset` in our code base, I know that it is most likely a data transfer object from the Collibra API.

We might at some point define our own internal `Asset` that might not have the same properties as the external definition. Having the root namespace for our own definitions is a boon.

2022-06-09 12:26 UTC, ovineq commented on config.ts
>    AUTH_AUTHORITY: process.env.NEXT_PUBLIC_AUTH_AUTHORITY ?? "",
Talked in the standup this morning about fixing this at a later date.

2022-06-09 12:26 UTC, ovineq commented on config.ts
>    AUTH_AUTHORITY: process.env.NEXT_PUBLIC_AUTH_AUTHORITY ?? "",
Talked in the standup this morning about fixing this at a later date.

2022-06-13 14:54 UTC, merged